### ISSUE TITLE
pip install does not include README.md and fails

### ISSUE THREAD

**Issue by tenspd137** [endangeredoxen/fileio#4]
pychar2) imagepcboi@USID05D-MIG322 C:\Miniconda3\envs\pychar2\Lib\site-packages
$ pip install fivecentfileio
Collecting fivecentfileio
  Using cached fivecentfileio-0.2.9.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Miniconda3\envs\pychar2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\imagepcboi\\AppData\\Local\\Temp\\pip-install-_58pl6m5\\fivecentfileio\\setup.py'"'"'; __file__='"'"'C:\\Users\\imagepcboi\\AppData\\Local\\Temp\\pip-install-_58pl6m5\\fivecentfileio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\imagepcboi\AppData\Local\Temp\pip-pip-egg-info-42w74o5z'
         cwd: C:\Users\imagepcboi\AppData\Local\Temp\pip-install-_58pl6m5\fivecentfileio\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      **File "C:\Users\imagepcboi\AppData\Local\Temp\pip-install-_58pl6m5\fivecentfileio\setup.py", line 12, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'**
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by endangeredoxen** [comment]
fixed in latest release
